language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: tHfWWThKs5y8HOW3Ykbi5cr+mDZBqyCoznV3wcfV2ikTl9qOcybgXfvcvYciOiGBHwurIbx6vJph8VjS7XcO7eaDENU3dzJ9RhfgdxsKfJMCU+niXQPTtD+xoLjzYtHL0nRztOi1OS0RA4YFFHIbyGETvTmpb5grujrLvJZkpU59aBfL9nIAdqwNNnyoFnSxk0vDVyhY5LB7EvlbkDTkSGTCD1DVXqG0+qceLQCojGmG8OAjUHX+Zk51wO2upgqKn2q7d8XPJ5enWzscIfFfjgKpOvLpQPgFEqmcqyOp9CwHJ7HwdrHzgwvspKZOpWlubUk0OrLvqcuNNQgPpjds2U4pN7yxIkftAeMVs+2mk6qCy7sxOoZNBuD5VTXN6jQw+ey4t2a4lT6v/wwvyX42434r3wRIQCBtMjQkZqegr0UtqC77E3Ek4M7ggfmi5fORhQ9OQvuZondosFaGKchw0VHlD90yvE47Hob4CvfEP3cpRMrUlHTy0jiIYxTA9juZ5tYEfGuNNIETVsOUb3A45cVTD2hFIKSurzL8ba4fPC5cSIq4E+AccWVCiWfOVEAxBvDmnQY8lieXjvqMma+YDF/Hmtag5MZ93XVX9k1LpLix5bj9Q0LcZb9H0FI95Mv7SLTz5yFU7aAWfqhv9FpF9TosFhdjLCf9AQ9qgcdpL8s=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client==0.12.5
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- yarn test
- yarn build:browser
after_success:
- test $TRAVIS_BRANCH = "master" && yarn run deploy:travis -- --branch=build
