language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: FbVoHMuTEJ4RvU+Ax1wIxbOD3/QR41PKDNWtqIY7Ad1sJtmPf697/9hi2xXMaF/w/3SOowp2v7/QGacCnROgQnmEKmYVXLS+dCRSYIoqlizgyEe2o6Bll9pnxv7XtAKTXs1JWvi0csmhF6C8Hr3KCOsidSEujvq+BJ2hvSdxpMJ8BematMTW50gL4rmFBc5UijwwDb3nfW3hzSnX2azePFYXTeVN+KPJRvs4x3ZVy6qALRtv58sc5jUEnQMv9fIIeEet8r7K4IwgjpdLEDtV7JfOeD6HOHtpNku/L0f1bBZfElHCqL4pc8kyrUX5PPIxSPXFO6zLniVMCEOd7Ng8yQV2SuyYEmIA6GWkuTLXm137GAM3NntJdMyipEBNASkqgpOvKnjLNxiPoaGRowh42YYATevUc62HdpCDFZPpIpOq1rCGhmO+tUMJ7nidwhEyUPhSHBCyXTVkJzZp28dzfJc5XZUsRtohJnCmO+NQkPetZfcrDL13gYidCzh/Tp/Tfd4so3h7rlR+ArZc7QLIDqJSKbAe463HyRoL3UeHtFhzcn+jzxN1/YF6CrMa1wzN6bEBovfqmz1I5Midr6HlKl8MoMTHKadldCZboCr1lyH42ASeGHrtok9YdI/3G/nEmJD8FnhtRotZSWFCXC0nqPTtS5M1l18ijOIJEO7t/7E=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- yarn test
- yarn build:browser
after_success:
- test $TRAVIS_BRANCH = "master" && yarn run deploy:travis -- --branch=build
